"""Tests for database models."""

import uuid
from datetime import datetime
from unittest.mock import MagicMock, patch

import pytest

from obsidian_rag.database.models import (
    ArrayType,
    Document,
    Task,
    TaskPriority,
    TaskStatus,
    Vault,
)


class TestDocument:
    """Test cases for Document model."""

    def test_create_document(self):
        """Test creating a document."""
        doc = Document(
            vault_id=uuid.uuid4(),
            file_path="file.md",
            file_name="file.md",
            content="Test content",
            checksum_md5="abc123",
            created_at_fs=datetime.now(),
            modified_at_fs=datetime.now(),
        )

        # ID is auto-generated by database, None until persisted
        assert doc.file_path == "file.md"
        assert doc.checksum_md5 == "abc123"

    def test_document_with_tags(self):
        """Test document with tags array."""
        doc = Document(
            vault_id=uuid.uuid4(),
            file_path="file.md",
            file_name="file.md",
            content="Test content",
            checksum_md5="abc123",
            created_at_fs=datetime.now(),
            modified_at_fs=datetime.now(),
            tags=["tag1", "tag2", "tag3"],
        )

        assert doc.tags == ["tag1", "tag2", "tag3"]

    def test_document_with_metadata(self):
        """Test document with frontmatter metadata."""
        doc = Document(
            vault_id=uuid.uuid4(),
            file_path="file.md",
            file_name="file.md",
            content="Test content",
            checksum_md5="abc123",
            created_at_fs=datetime.now(),
            modified_at_fs=datetime.now(),
            frontmatter_json={"kind": "article", "author": "Test", "version": 1.0},
        )

        assert doc.frontmatter_json is not None
        assert doc.frontmatter_json.get("kind") == "article"
        assert doc.frontmatter_json.get("author") == "Test"
        assert doc.frontmatter_json.get("version") == 1.0


class TestTask:
    """Test cases for Task model."""

    def test_create_task(self):
        """Test creating a task associated with a document."""
        task = Task(
            document_id=uuid.uuid4(),
            line_number=5,
            raw_text="- [ ] A test task",
            status=TaskStatus.NOT_COMPLETED.value,
            description="A test task",
            priority=TaskPriority.NORMAL.value,
        )

        # ID is auto-generated by database, None until persisted
        assert task.status == TaskStatus.NOT_COMPLETED.value

    def test_task_all_status_values(self):
        """Test task with all status values."""
        statuses = [
            TaskStatus.NOT_COMPLETED.value,
            TaskStatus.COMPLETED.value,
            TaskStatus.IN_PROGRESS.value,
            TaskStatus.CANCELLED.value,
        ]

        for i, status in enumerate(statuses):
            task = Task(
                document_id=uuid.uuid4(),
                line_number=i,
                raw_text=f"- [ ] Task {i}",
                status=status,
                description=f"Task {i}",
            )
            assert task.status == status

    def test_task_with_all_fields(self):
        """Test task with all optional fields set."""
        from datetime import date

        task = Task(
            document_id=uuid.uuid4(),
            line_number=1,
            raw_text="- [ ] Task [due:: 2024-03-15]",
            status=TaskStatus.NOT_COMPLETED.value,
            description="Task",
            tags=["important", "work"],
            repeat="FREQ=DAILY",
            scheduled=date(2024, 3, 10),
            due=date(2024, 3, 15),
            completion=None,
            priority=TaskPriority.HIGH.value,
            custom_metadata={"project": "test"},
        )

        assert task.tags == ["important", "work"]
        assert task.repeat == "FREQ=DAILY"
        assert task.due is not None
        assert task.due.year == 2024
        assert task.priority == TaskPriority.HIGH.value
        assert task.custom_metadata == {"project": "test"}


class TestArrayType:
    """Test cases for ArrayType TypeDecorator."""

    def test_array_type_loads_postgresql_dialect(self):
        """Test ArrayType loads PG_ARRAY for PostgreSQL dialect."""
        from sqlalchemy.dialects.postgresql import dialect as pg_dialect

        array_type = ArrayType()
        impl = array_type.load_dialect_impl(pg_dialect())

        # Should use PostgreSQL ARRAY type (class name may vary by driver)
        assert "ARRAY" in impl.__class__.__name__

    def test_array_type_raises_for_non_postgresql_dialect(self):
        """Test ArrayType raises RuntimeError for non-PostgreSQL dialect."""
        from sqlalchemy.dialects.sqlite import dialect as sqlite_dialect

        array_type = ArrayType()

        with pytest.raises(RuntimeError, match="only supports PostgreSQL"):
            array_type.load_dialect_impl(sqlite_dialect())


class TestDocumentRepr:
    """Test cases for Document __repr__."""

    def test_document_repr(self):
        """Test Document __repr__ method."""
        doc = Document(
            file_path="/test/file.md",
            file_name="file.md",
            content="Test",
            checksum_md5="abc123",
            created_at_fs=datetime.now(),
            modified_at_fs=datetime.now(),
        )
        repr_str = repr(doc)

        assert "Document" in repr_str
        assert "/test/file.md" in repr_str


class TestTaskRepr:
    """Test cases for Task __repr__."""

    def test_task_repr(self):
        """Test Task __repr__ method."""
        task = Task(
            document_id=uuid.uuid4(),
            line_number=1,
            raw_text="- [ ] Test task",
            status="not_completed",
            description="Test task description",
        )
        repr_str = repr(task)

        assert "Task" in repr_str
        assert "not_completed" in repr_str
