"""LLM provider base classes and interfaces."""

import logging
from abc import ABC, abstractmethod

log = logging.getLogger(__name__)


class EmbeddingProvider(ABC):
    """Abstract base class for embedding providers.

    Implementations must provide methods to generate embeddings for text.

    """

    @abstractmethod
    def generate_embedding(self, text: str) -> list[float]:
        """Generate embedding vector for text.

        Args:
            text: The text to embed.

        Returns:
            List of float values representing the embedding vector.

        Raises:
            EmbeddingError: If embedding generation fails.

        """
        # pragma: no cover

    @abstractmethod
    def get_dimension(self) -> int:
        """Get the dimension of embeddings generated by this provider.

        Returns:
            The embedding dimension (e.g., 1536 for OpenAI).

        """
        # pragma: no cover


class ChatProvider(ABC):
    """Abstract base class for chat/LLM providers.

    Implementations must provide methods for chat completions.

    """

    @abstractmethod
    def chat(self, messages: list[dict[str, str]], **kwargs: object) -> str:
        """Send chat messages and get a response.

        Args:
            messages: List of message dicts with 'role' and 'content' keys.
            **kwargs: Additional provider-specific parameters.

        Returns:
            The response text from the model.

        Raises:
            ChatError: If the chat request fails.

        """
        # pragma: no cover


class ProviderError(Exception):
    """Base exception for provider errors."""


class EmbeddingError(ProviderError):
    """Exception raised when embedding generation fails."""


class ChatError(ProviderError):
    """Exception raised when chat request fails."""
