"""LLM provider base classes and interfaces."""

import logging
from abc import ABC, abstractmethod
from typing import Any

log = logging.getLogger(__name__)


class EmbeddingProvider(ABC):
    """Abstract base class for embedding providers.

    Implementations must provide methods to generate embeddings for text.

    """

    @abstractmethod
    def generate_embedding(self, text: str) -> list[float]:
        """Generate embedding vector for text.

        Args:
            text: The text to embed.

        Returns:
            List of float values representing the embedding vector.

        Raises:
            EmbeddingError: If embedding generation fails.

        """
        pass  # pragma: no cover

    @abstractmethod
    def get_dimension(self) -> int:
        """Get the dimension of embeddings generated by this provider.

        Returns:
            The embedding dimension (e.g., 1536 for OpenAI).

        """
        pass  # pragma: no cover


class ChatProvider(ABC):
    """Abstract base class for chat/LLM providers.

    Implementations must provide methods for chat completions.

    """

    @abstractmethod
    def chat(self, messages: list[dict[str, str]], **kwargs) -> str:
        """Send chat messages and get a response.

        Args:
            messages: List of message dicts with 'role' and 'content' keys.
            **kwargs: Additional provider-specific parameters.

        Returns:
            The response text from the model.

        Raises:
            ChatError: If the chat request fails.

        """
        pass  # pragma: no cover


class ProviderError(Exception):
    """Base exception for provider errors."""

    pass


class EmbeddingError(ProviderError):
    """Exception raised when embedding generation fails."""

    pass


class ChatError(ProviderError):
    """Exception raised when chat request fails."""

    pass


class ProviderFactory:
    """Factory for creating provider instances.

    Creates appropriate provider instances based on configuration.

    """

    @staticmethod
    def create_embedding_provider(
        provider_name: str,
        **config,
    ) -> EmbeddingProvider:  # type: ignore[no-untyped-def]
        """Create an embedding provider instance.

        Args:
            provider_name: Name of the provider ('openai', 'huggingface', 'openrouter').
            **config: Provider-specific configuration.

        Returns:
            EmbeddingProvider instance.

        Raises:
            ValueError: If the provider name is unknown.

        """
        _msg = f"Creating embedding provider: {provider_name}"
        log.debug(_msg)

        # Import here to avoid circular dependencies
        if provider_name == "openai":
            from obsidian_rag.llm.providers import OpenAIEmbeddingProvider

            return OpenAIEmbeddingProvider(**config)
        elif provider_name == "huggingface":
            from obsidian_rag.llm.providers import HuggingFaceEmbeddingProvider

            return HuggingFaceEmbeddingProvider(**config)
        elif provider_name == "openrouter":
            from obsidian_rag.llm.providers import OpenRouterEmbeddingProvider

            return OpenRouterEmbeddingProvider(**config)
        else:
            _msg = f"Unknown embedding provider: {provider_name}"
            log.error(_msg)
            raise ValueError(_msg)

    @staticmethod
    def create_chat_provider(
        provider_name: str,
        **config,
    ) -> ChatProvider:  # type: ignore[no-untyped-def]
        """Create a chat provider instance.

        Args:
            provider_name: Name of the provider ('openai', 'openrouter').
            **config: Provider-specific configuration.

        Returns:
            ChatProvider instance.

        Raises:
            ValueError: If the provider name is unknown.

        """
        _msg = f"Creating chat provider: {provider_name}"
        log.debug(_msg)

        if provider_name == "openai":
            from obsidian_rag.llm.providers import OpenAIChatProvider

            return OpenAIChatProvider(**config)
        elif provider_name == "openrouter":
            from obsidian_rag.llm.providers import OpenRouterChatProvider

            return OpenRouterChatProvider(**config)
        else:
            _msg = f"Unknown chat provider: {provider_name}"
            log.error(_msg)
            raise ValueError(_msg)
