"""Type stubs for obsidian_rag.llm.base module.

This stub file contains type annotations for the abstract base classes
without implementation details. It allows type checkers to verify
types without requiring coverage on abstract method signatures.

"""

from abc import ABC, abstractmethod

class EmbeddingProvider(ABC):
    """Abstract base class for embedding providers."""

    @abstractmethod
    def generate_embedding(self, text: str) -> list[float]:
        """Generate embedding vector for text.

        Args:
            text: The text to embed.

        Returns:
            List of float values representing the embedding vector.

        Raises:
            EmbeddingError: If embedding generation fails.

        """
        ...

    @abstractmethod
    def get_dimension(self) -> int:
        """Get the dimension of embeddings generated by this provider.

        Returns:
            The embedding dimension (e.g., 1536 for OpenAI).

        """
        ...

class ChatProvider(ABC):
    """Abstract base class for chat/LLM providers."""

    @abstractmethod
    def chat(self, messages: list[dict[str, str]], **kwargs: object) -> str:
        """Send chat messages and get a response.

        Args:
            messages: List of message dicts with 'role' and 'content' keys.
            **kwargs: Additional provider-specific parameters.

        Returns:
            The response text from the model.

        Raises:
            ChatError: If the chat request fails.

        """
        ...

class ProviderError(Exception):
    """Base exception for provider errors."""

class EmbeddingError(ProviderError):
    """Exception raised when embedding generation fails."""

class ChatError(ProviderError):
    """Exception raised when chat request fails."""
